### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by franciscogimeno2000** [VirtusLab/Ariadne-Bootloader#1]
Hello and thank you for your work in the boot loader.

I have a question, how to use the boot loader with dynamic ip?

Thank you very much.

**Comment by jkramarz** [comment]
Dynamic like DHCP in LAN?

**Comment by franciscogimeno2000** [comment]
yes, 
I am using the SEM Bootloader for Arduino that is based on this code, only that adding support for the chip Wiznet5100, W5200 and W5500

**Comment by jkramarz** [comment]
I don't think it is. This one is a out-of-tree fork for very specific hardware. Please take a look at https://github.com/codebndr/Ariadne-Bootloader

**Comment by franciscogimeno2000** [comment]
I have reviewed this project and nothing appears to be able to use
the dynamic ip. I've also searched in google and there's nothing.

**Comment by franciscogimeno2000** [comment]
Anyway, thanks
